
SUBSCRIBE_HEARTBEAT_TIMEOUT_SECONDS = 10
SUBSCRIBE_HEARTBEAT_TOPIC = "cropwaifu/heartbeat"
SUBSCRIBE_CTRL_MSG_TOPIC = "cropwaifu/respond"

PUBLISH_RESENT_MAX_RETRIES = 3
PUBLISH_TIMEOUT_SECONDS = 5
PUBLISH_ERR_MAX_RETRIES = 3
PUBLISH_CTRL_MSG_TPPIC = "cropwaifu/control"
PUBLISH_CTRL_QOS = 0
